# Generated by Django 4.0 on 2021-12-18 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilova', '0003_portfolio_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='definition1',
            new_name='definition',
        ),
        migrations.RemoveField(
            model_name='service',
            name='definition2',
        ),
        migrations.RemoveField(
            model_name='service',
            name='definition3',
        ),
        migrations.RemoveField(
            model_name='service',
            name='definition4',
        ),
        migrations.RemoveField(
            model_name='service',
            name='definition5',
        ),
    ]
